version: "3"
services:
  vsnet-game:
    container_name: "vsnet-game"
    build:
      context: ../vsnet-game
      dockerfile: Dockerfile.dev
    volumes:
      - ../vsnet-game/src:/app/src
    expose:
      - "4000"
      - "4001"
      - "4002"
      - "4003"
    ports:
      - "4000:4000"
      - "4001:4001"
      - "4002:4002"
      - "4003:4003"
    restart: always
  vsnet-social:
    container_name: "vsnet-social"
    build:
      context: ../vsnet-social
      dockerfile: Dockerfile.dev
    volumes:
      - ../vsnet-social/src:/app/src
    expose:
      - "3000"
    ports:
      - "3000:3000"
    depends_on:
      - vsnet-social-pubsub
    restart: always
  vsnet-social-pubsub:
    container_name: "vsnet-social-pubsub"
    image: redis
    expose:
      - "6379"
    ports:
      - "6379:6379"
    restart: always
  vsnet-api:
    container_name: "vsnet-api"
    build:
      context: ../vsnet-api
      dockerfile: Dockerfile.dev
    volumes:
      - ../vsnet-api/src:/app/src
    expose:
      - "8000"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    restart: always
  vsnet-auth:
    container_name: "vsnet-auth"
    build:
      context: ../vsnet-auth
      dockerfile: Dockerfile.dev
    volumes:
      - ../vsnet-auth/src:/app/src
    expose:
      - "8000"
    ports:
      - "8001:8000"
    depends_on:
        - vsnet-api
    restart: always
  postgres:
    container_name: "vsnet-postgres"
    image: postgres:10.2-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: makeshift
    expose:
      - "5432"
    ports:
      - "5432:5432"
